services:
  postgres:
    image: postgres:17.4
    container_name: customer-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customerdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db-migrate:
    image: flyway/flyway:11
    container_name: customerdb-migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://customer-db/customerdb
      FLYWAY_USER: user
      FLYWAY_PASSWORD: password
      FLYWAY_POSTGRESQL_TRANSACTIONAL_LOCK: "false"
    command:
      - migrate
      - -X
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - postgres

volumes:
  postgres_data:
